-- Add more countries that are not under US sanctions (comprehensive list)
INSERT INTO countries (name, code, currency, is_active) VALUES
-- Europe
('Albania', 'AL', 'ALL', true),
('Andorra', 'AD', 'EUR', true),
('Austria', 'AT', 'EUR', true),
('Belgium', 'BE', 'EUR', true),
('Bulgaria', 'BG', 'BGN', true),
('Croatia', 'HR', 'EUR', true),
('Cyprus', 'CY', 'EUR', true),
('Czech Republic', 'CZ', 'CZK', true),
('Denmark', 'DK', 'DKK', true),
('Estonia', 'EE', 'EUR', true),
('Finland', 'FI', 'EUR', true),
('Greece', 'GR', 'EUR', true),
('Hungary', 'HU', 'HUF', true),
('Iceland', 'IS', 'ISK', true),
('Ireland', 'IE', 'EUR', true),
('Italy', 'IT', 'EUR', true),
('Latvia', 'LV', 'EUR', true),
('Liechtenstein', 'LI', 'CHF', true),
('Lithuania', 'LT', 'EUR', true),
('Luxembourg', 'LU', 'EUR', true),
('Malta', 'MT', 'EUR', true),
('Monaco', 'MC', 'EUR', true),
('Netherlands', 'NL', 'EUR', true),
('Norway', 'NO', 'NOK', true),
('Poland', 'PL', 'PLN', true),
('Portugal', 'PT', 'EUR', true),
('Romania', 'RO', 'RON', true),
('San Marino', 'SM', 'EUR', true),
('Slovakia', 'SK', 'EUR', true),
('Slovenia', 'SI', 'EUR', true),
('Spain', 'ES', 'EUR', true),
('Sweden', 'SE', 'SEK', true),
('Switzerland', 'CH', 'CHF', true),
('Vatican City', 'VA', 'EUR', true),

-- Asia Pacific
('Bangladesh', 'BD', 'BDT', true),
('Bhutan', 'BT', 'BTN', true),
('Brunei', 'BN', 'BND', true),
('Cambodia', 'KH', 'KHR', true),
('India', 'IN', 'INR', true),
('Indonesia', 'ID', 'IDR', true),
('Kazakhstan', 'KZ', 'KZT', true),
('Kyrgyzstan', 'KG', 'KGS', true),
('Laos', 'LA', 'LAK', true),
('Malaysia', 'MY', 'MYR', true),
('Maldives', 'MV', 'MVR', true),
('Mongolia', 'MN', 'MNT', true),
('Nepal', 'NP', 'NPR', true),
('New Zealand', 'NZ', 'NZD', true),
('Papua New Guinea', 'PG', 'PGK', true),
('Philippines', 'PH', 'PHP', true),
('Singapore', 'SG', 'SGD', true),
('South Korea', 'KR', 'KRW', true),
('Sri Lanka', 'LK', 'LKR', true),
('Taiwan', 'TW', 'TWD', true),
('Tajikistan', 'TJ', 'TJS', true),
('Thailand', 'TH', 'THB', true),
('Timor-Leste', 'TL', 'USD', true),
('Turkmenistan', 'TM', 'TMT', true),
('Uzbekistan', 'UZ', 'UZS', true),
('Vietnam', 'VN', 'VND', true),

-- Americas
('Argentina', 'AR', 'ARS', true),
('Bahamas', 'BS', 'BSD', true),
('Barbados', 'BB', 'BBD', true),
('Belize', 'BZ', 'BZD', true),
('Bolivia', 'BO', 'BOB', true),
('Chile', 'CL', 'CLP', true),
('Colombia', 'CO', 'COP', true),
('Costa Rica', 'CR', 'CRC', true),
('Dominica', 'DM', 'XCD', true),
('Dominican Republic', 'DO', 'DOP', true),
('Ecuador', 'EC', 'USD', true),
('El Salvador', 'SV', 'USD', true),
('Grenada', 'GD', 'XCD', true),
('Guatemala', 'GT', 'GTQ', true),
('Guyana', 'GY', 'GYD', true),
('Haiti', 'HT', 'HTG', true),
('Honduras', 'HN', 'HNL', true),
('Jamaica', 'JM', 'JMD', true),
('Mexico', 'MX', 'MXN', true),
('Panama', 'PA', 'PAB', true),
('Paraguay', 'PY', 'PYG', true),
('Peru', 'PE', 'PEN', true),
('Saint Kitts and Nevis', 'KN', 'XCD', true),
('Saint Lucia', 'LC', 'XCD', true),
('Saint Vincent and the Grenadines', 'VC', 'XCD', true),
('Suriname', 'SR', 'SRD', true),
('Trinidad and Tobago', 'TT', 'TTD', true),
('Uruguay', 'UY', 'UYU', true),

-- Africa
('Algeria', 'DZ', 'DZD', true),
('Angola', 'AO', 'AOA', true),
('Benin', 'BJ', 'XOF', true),
('Botswana', 'BW', 'BWP', true),
('Burkina Faso', 'BF', 'XOF', true),
('Cameroon', 'CM', 'XAF', true),
('Cape Verde', 'CV', 'CVE', true),
('Central African Republic', 'CF', 'XAF', true),
('Chad', 'TD', 'XAF', true),
('Comoros', 'KM', 'KMF', true),
('Republic of the Congo', 'CG', 'XAF', true),
('Democratic Republic of the Congo', 'CD', 'CDF', true),
('Djibouti', 'DJ', 'DJF', true),
('Egypt', 'EG', 'EGP', true),
('Equatorial Guinea', 'GQ', 'XAF', true),
('Eswatini', 'SZ', 'SZL', true),
('Ethiopia', 'ET', 'ETB', true),
('Gabon', 'GA', 'XAF', true),
('Gambia', 'GM', 'GMD', true),
('Ghana', 'GH', 'GHS', true),
('Guinea', 'GN', 'GNF', true),
('Guinea-Bissau', 'GW', 'XOF', true),
('Ivory Coast', 'CI', 'XOF', true),
('Kenya', 'KE', 'KES', true),
('Lesotho', 'LS', 'LSL', true),
('Liberia', 'LR', 'LRD', true),
('Madagascar', 'MG', 'MGA', true),
('Malawi', 'MW', 'MWK', true),
('Mali', 'ML', 'XOF', true),
('Mauritania', 'MR', 'MRU', true),
('Mauritius', 'MU', 'MUR', true),
('Morocco', 'MA', 'MAD', true),
('Mozambique', 'MZ', 'MZN', true),
('Namibia', 'NA', 'NAD', true),
('Niger', 'NE', 'XOF', true),
('Nigeria', 'NG', 'NGN', true),
('Rwanda', 'RW', 'RWF', true),
('Sao Tome and Principe', 'ST', 'STN', true),
('Senegal', 'SN', 'XOF', true),
('Seychelles', 'SC', 'SCR', true),
('Sierra Leone', 'SL', 'SLL', true),
('South Africa', 'ZA', 'ZAR', true),
('Tanzania', 'TZ', 'TZS', true),
('Togo', 'TG', 'XOF', true),
('Tunisia', 'TN', 'TND', true),
('Uganda', 'UG', 'UGX', true),
('Zambia', 'ZM', 'ZMW', true),

-- Middle East
('Bahrain', 'BH', 'BHD', true),
('Israel', 'IL', 'ILS', true),
('Jordan', 'JO', 'JOD', true),
('Kuwait', 'KW', 'KWD', true),
('Oman', 'OM', 'OMR', true),
('Qatar', 'QA', 'QAR', true),
('Saudi Arabia', 'SA', 'SAR', true),
('Turkey', 'TR', 'TRY', true),
('United Arab Emirates', 'AE', 'AED', true),

-- Oceania
('Fiji', 'FJ', 'FJD', true),
('Kiribati', 'KI', 'AUD', true),
('Marshall Islands', 'MH', 'USD', true),
('Micronesia', 'FM', 'USD', true),
('Nauru', 'NR', 'AUD', true),
('Palau', 'PW', 'USD', true),
('Samoa', 'WS', 'WST', true),
('Solomon Islands', 'SB', 'SBD', true),
('Tonga', 'TO', 'TOP', true),
('Tuvalu', 'TV', 'AUD', true),
('Vanuatu', 'VU', 'VUV', true)

ON CONFLICT (name) DO NOTHING;