// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itpbaiivmxeqpcbchauf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0cGJhaWl2bXhlcXBjYmNoYXVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzcyNjksImV4cCI6MjA2NTU1MzI2OX0._sAUYmIsHai5UoAUYEL_frxXUFwik4evECmVmZvbtDA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);